<?php

declare(strict_types=1);
//[STAMP] 26932f9dc2cdab4631f2680565d34834

namespace Forge\App\Tests\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();
}
